### PR TITLE
Update project team members

### PR DESCRIPTION
**Pull request by sathvikl**
Removed Dave Stewart, added myself.

### CODE REVIEW

**Comment by mhdawson** [comment]
sorry I've missed this will look at landing these next week.

**Comment by uttampawar** [comment]
@mhdawson If you do accept and merge this, please ignore another PR by me https://github.com/nodejs/benchmarking/pull/104

**Comment by mhdawson** [comment]
Sorry I did them in the wrong order, if you will participate instead of uttam can you update this PR to remove him and add yourself ?

**Comment by mhdawson** [comment]
@sathvikl ping

**Comment by sathvikl** [comment]
@mhdawson  sorry Mike I was out of office for a while. Uttam alone being there should be fine.

**Comment by mhdawson** [comment]
Sounds like this can be closed then.

**Pull request closed without merging**
