### PR TITLE
Update path to style sheet

### PR DESCRIPTION
**Pull request by richardlau**
Refs: https://github.com/nodejs/nodejs.org/pull/2544

### CODE REVIEW

**Comment by XhmikosR** [comment]
Is there a list of such sites? I see some things like referencing old icons and I'd like to fix those too.

**Comment by XhmikosR** [comment]
@mhdawson this is now obsolete since you merged #290

**Comment by mhdawson** [comment]
@richardlau can you rebase

**Comment by XhmikosR** [comment]
@mhdawson https://github.com/nodejs/benchmarking/pull/289#issuecomment-536729339

This can be closed now.

**Comment by mhdawson** [comment]
@XhmikosR was not 100% sure but thought that might be the case. I'll let @richardlau close.

**Comment by XhmikosR** [comment]
I'm 100% sure because I broke it in the first place :P

**Comment by richardlau** [comment]
This was included in https://github.com/nodejs/benchmarking/pull/290.

**Pull request closed without merging**
