### PR TITLE
Add @bmeurer to WG

### PR DESCRIPTION
**Pull request by bmeurer**

### CODE REVIEW

**Comment by kunalspathak** [comment]
+1 from me.

**Comment by bmeurer** [comment]
Do I need to do anything here to move forward with it?

**Comment by kunalspathak** [comment]
Nope. @mhdawson  should be able to merge this PR.

**Comment by mhdawson** [comment]
+1 will merge when I have time.

**Comment by mhdawson** [comment]
Landed as 415bec691bcd0570331788594b2e99b4e4dfd888, welcome abord.

**Pull request closed without merging**
