### PR TITLE
src: drop 7.x results from charts

### PR DESCRIPTION
**Pull request by kfarnung**
Switched 8.x to use the "grey" color from 7.x

### CODE REVIEW

**Comment by mhdawson** [comment]
Landed as 66e82bf30a408604bd1b5e578d878b971ff4d8c0

Will check tomorrow after schedule runs are complete to validate all looks good.

**Comment by mhdawson** [comment]
All looks good at benchmarking.nodejs.org.  @kfarnung thanks !.

**Comment by kfarnung** [comment]
@mhdawson No problem!

**Pull request closed without merging**
