### PR TITLE
doc: update use cases and case coverage

### PR DESCRIPTION
**Pull request by davisjam**
- Split use cases into "web stack" and "other uses".
- Introduce new use cases based on the Node.js Foundation's
  Application Showcase (https://foundation.nodejs.org/resources/app-showcase)
	and other popular Node.js software I have encountered.

### CODE REVIEW

**Comment by davisjam** [comment]
This PR was inspired by the discussion at the Sept. 18 WG meeting (minutes are in #241).

If anyone is interested, [here](https://docs.google.com/spreadsheets/d/1T1AS7V-ixiqqlU6z00N7lI3gqpXtPLYaCabKzPboxhE/edit?usp=sharing) is a Google Doc with:
- The 116 Node.js apps listed as of Sept. 2018, plus some others (Micro'15, existing application benchmarks)
- A preliminary label of the App Showcase apps into one of the [use cases](https://github.com/nodejs/benchmarking/blob/master/docs/use_cases.md)
- A link to its GitHub if the app is open source

**Comment by davisjam** [comment]
I have some ideas about workloads to add for use cases. Is this thread a good place to discuss them?

**Comment by mhdawson** [comment]
In respect to: 

```
I have some ideas about workloads to add for use cases. Is this thread a good place to discuss them?
```

I think an issue as opposed to a PR would be a better place for a longer running discussion.

**Comment by mhdawson** [comment]
@davisjam that is a great list to have along with the classification of the area.  Using the Node.js collection is a great idea.

**Comment by davisjam** [comment]
@mhdawson 
> Using the Node.js collection is a great idea.

It was *your* idea ;-)

**Comment by davisjam** [comment]
@jorangreef, I think you might have some comments on the "systems software" use case and perhaps others?

**Comment by mhdawson** [comment]
@davisjam -> "It was your idea ;-)"

I guess that is why I liked it sooo much even though I forgot that.  But thanks for actually putting it into action :)

**Comment by jorangreef** [comment]
Thanks @davisjam, replied in https://github.com/nodejs/benchmarking/issues/6#issuecomment-426628035

**Pull request merged**
