### PR TITLE
Use valid HTML and Node.js website style

### PR DESCRIPTION
**Pull request by fhemberger**
To make the site look like it belongs to the node.js project, I used the base HTML of the current website as "frame" for your content. Also made the content valid HTML5 markup.

### CODE REVIEW

**Comment by rvagg** [comment]
@fhemberger there's no build step, just a clone an rsync into place so what you've done is appropriate. If you think there's a case for a build step then you could propose it. I'd be happy to do the work on the Build side if they want it here.

Here's a screenshot of @fhemberger's proposal:

screenshot from 2016-02-27 11-51-32

(lgtm fwiw)

**Comment by fhemberger** [comment]
@rvagg No, I don't think we need a build step for this. I've linked every asset we need directly to nodejs.org, so all the working group needs to do in the future is appending new benchmark graphs.

**Comment by mhdawson** [comment]
Sorry not sure why I did not see the notification for this earlier.  Will take a look today

**Comment by mhdawson** [comment]
lgtm

**Comment by mhdawson** [comment]
landed as c9ebc312d12062d0b9c45010c094f771970d9b68.  @fhemberger thanks for the help. Will close https://github.com/nodejs/nodejs.org/issues/540

**Pull request closed without merging**
