### PR TITLE
doc: add minutes for meeting 18 sep 2018

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by mhdawson** [comment]
@nodejs/benchmarking can I get a review?

**Comment by davisjam** [comment]
LGTM (but I'm not a member).

Following up on the discussion about new benchmarks:

I've got some initial results from the Node.js Foundation Application Showcase. I'm working on further analysis. How would you folks like to see the results? Not sure that either Issue or PR is the right way to report this.

**Comment by mhdawson** [comment]
@uttampawar, @gareth-ellis  could your review?

**Comment by mhdawson** [comment]
PR-URL: https://github.com/nodejs/benchmarking/pull/241
Reviewed-By: Gareth Ellis <gareth.ellis@uk.ibm.com>

**Pull request merged**
