### PR TITLE
tools: fix setTimeout() in tools/acceptResults/bridge.js

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by mhdawson** [comment]
@Trott is there any context on this.  Does it fix a failure you've seen?

**Comment by mhdawson** [comment]
I can see the code should be fixed but wondering about where it was spotted and possibly what to check after its fixed.

**Comment by Trott** [comment]
> I can see the code should be fixed but wondering about where it was spotted and possibly what to check after its fixed.

I noticed it while looking at lgtim.io results for this repository. The other things in there are things that minimal linting would find, like `for i=0` rather than `for let i=0`. But this seemed like a genuine error that would probably escape notice by linters and I figured it would be uncontroversial and ought to be fixed whether or not linting and/or tests are added to the repository.

**Comment by Trott** [comment]
Polite bump! Can this land? If not, anything I can do to change that?

**Pull request merged**
