### PR TITLE
Dawson/avoid hang

### PR DESCRIPTION
**Pull request by mhdawson**
src: fixup to avoid dc-eis hang

### CODE REVIEW

**Comment by mhdawson** [comment]
Looks like it ran through fine.https://ci.nodejs.org/job/node-stress-single-test/1423/

**Comment by mhdawson** [comment]
@uttampawar if you review/approve this PR after checking it has everything from your original PR I can land tomorrow.

**Comment by uttampawar** [comment]
@mhdawson I've fixed all the hang-up issues we had seen. I' ve couple more changes in addition to my PR. Please wait for couple of days before landing. Let me do some more testing.

**Comment by mhdawson** [comment]
@uttampawar is there something wrong with whats in the PR already ?  I really wanted to be able to stop having to check for hanging jobs everyday ? 

I'd like to get at least the minimal change needed to avoid the hangs landed.

**Comment by uttampawar** [comment]
@mhdawson I finished my testing on my local machine as well on the nodejsbenchmarking infrastructure. I've not seen any hangup issue anymore. Sorry about the those issues earlier. But it's looks stable now. Feel free to take next step as you see fit. Please let me know what else I can do to help? I sincerely appreciate your time.

**Comment by mhdawson** [comment]
Thanks @uttampawar will land and update all jobs to use.  thanks for your help

**Comment by mhdawson** [comment]
Landed as e56278a5d3f3e1c52eb40620f19baafa40776be6

**Pull request closed without merging**
