### PR TITLE
www: add the needed CSS from the main site.

### PR DESCRIPTION
**Pull request by XhmikosR**
This unties the site from the upstream CSS, while keeping the same look.

Preview: <https://clever-stonebraker-c197dd.netlify.com/>

The missing images is because they are missing from the repo and I didn't generate them.

TODO:

- [ ] Move the other assets too like favicons, logo etc?

Refs https://github.com/nodejs/nodejs.org/pull/2635

Note that the CSS is only the required. Which means that if more elements are added at some point, their rules should be added manually here again.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Let's wait before merging, I'd like to add a comment about a couple of
selectors specific to this repo.

**Comment by mhdawson** [comment]
@XhmikosR ack, let me know when its ready to land.

**Comment by XhmikosR** [comment]
@mhdawson should be OK now

**Comment by XhmikosR** [comment]
Should we also move the other assets like the logo and favicons here too?

**Comment by mhdawson** [comment]
@XhmikosR I'm not sure why we would move them over?  We want to be consistent with the main site.  Is there more context for why it would make sense to move over more assets?

**Comment by XhmikosR** [comment]
Your call. I'd personally keep them separated. That way, I know they won't break, at least.

**Pull request merged**
