### PR TITLE
src: add octane chart to benchmarking.nodejs.org

### PR DESCRIPTION
**Pull request by mhdawson**
Add the link to the main page

@CurryKitten once last thing for the new benchmark to show up.

### CODE REVIEW

**Comment by mhdawson** [comment]
@gareth-ellis can you review.

**Comment by gareth-ellis** [comment]
lgtm

**Comment by mhdawson** [comment]
I did not change anything.  However, looking at the list of collaborators you were not there for some reason so I re-added you.  I don't see a log of changes if you know were I should look I'd be interested to see if I can figure out what happened.  

Do you have the review button now ?

**Comment by mhdawson** [comment]
Don't believe this is controversial since the other pieces have landed so will land now.

**Comment by gareth-ellis** [comment]
I removed myself from the collaborators in the repo as being in the nodejs / benchmarking team made me a collaborator here anyway and I wasn't sure if it was being listed in both places was confusing things.  

I've still not got the button , but if you look at the pr for September's meeting minutes (#59) I approved there, so I did have it at one point. I looked in the teams on the org and I did see I'm not in the members team, not sure if that has anything to do with it

**Comment by mhdawson** [comment]
landed as d912abf664d83b8cebbcd4ae6e41b3da58a71ece

**Comment by mhdawson** [comment]
I see you are in the benchmarking team.  Where is it that you are not ?

**Pull request closed without merging**
