### PR TITLE
update chartGen dependencies

### PR DESCRIPTION
**Pull request by Trott**
phantomjs is deprecated and insecure. Use phantomjs-prebuilt instead.

update mysql to secure version (later than 2.14.0)

add package-lock.json

### CODE REVIEW

**Comment by Trott** [comment]
> I think should be tested in advance.

Does that mean you'll do the testing, you're asking me to do the testing, or someone else?

**Comment by mhdawson** [comment]
It would be great if you could do the testing.  Otherwise, I'll eventually get to it but I'm not sure when that will be.

**Comment by Trott** [comment]
> It would be great if you could do the testing. Otherwise, I'll eventually get to it but I'm not sure when that will be.

Maybe I'm too easily intimidated by moderately long text files, but the setup described in benchmarkdata is a bit more than I'd like to go through to test this. Is there a benchmarking dev/test server by any chance? (Docker image maybe?)

**Comment by mhdawson** [comment]
There is the single bechmarking machine that we run the chart generation on. It is iojs-softlayer-benchmark-data and things are setup under the benchmark user (su - benchmark)

The setup there automatically pulls the latest from the repo.  What you could do to test is to commit the change, manually update the repo and then run the command to generate the charts (you can see the commands used from the crontab for the benchmarking user - chartcron is the one that generates the charts).  Then if runs ok then good, otherwise fix up or revert the commit.

**Comment by uttampawar** [comment]
I'll take a look at this one to verify new package.

**Comment by Trott** [comment]
Polite ping! Anything I can do here to help move this one forward?

**Comment by Trott** [comment]
This seems like perhaps it has stalled. Would it be appropriate to put it on the Benchmarking WG agenda to see if someone can champion it and move it forward? Or is that a bit much? I'd really like for our repositories to set a good example in terms of upgrading/replacing insecure dependencies.

**Comment by mhdawson** [comment]
@Trott you can always the requested validation if you really want this to land now.  I think you already have access to the machine....

**Comment by Trott** [comment]
> @Trott you can always do the requested validation if you really want this to land now. I think you already have access to the machine....

I tried to ssh into iojs-softlayer-benchmark-data but that host does not exist in my .ssh/config even after synching my build repo and running the write-ssh-config.yml ansible playbook. No hosts in my .ssh/config have `benchmark` in the name, and none of the other `softlayer` hosts look like the right ones:

```console
$ grep softlayer ~/.ssh/config 
Host infra-softlayer-debian8-x64-1 registry-mirror
Host infra-softlayer-ubuntu1404-x64-1 ci-release
Host infra-softlayer-ubuntu1404-x64-2 
Host release-softlayer-centos5-x86-1 
Host release-softlayer-centos6-x64-1 
Host test-softlayer-centos5-x64-1 
Host test-softlayer-centos5-x64-2 
Host test-softlayer-centos6-x64-1 
Host test-softlayer-centos6-x64-2 
Host test-softlayer-centos7-x64-1 
Host test-softlayer-debian8-x86-1 
Host test-softlayer-debian9-x64-1 
Host test-softlayer-ubuntu1404-x64-1 
Host test-softlayer-ubuntu1404-x86-1 
Host test-softlayer-ubuntu1604-x64-1 jenkins-workspace-3
Host test-softlayer-ubuntu1604_docker-x64-1 
$ 
```
I'm sure I'm doing something wrong. What is it, though?

**Comment by mhdawson** [comment]
Somebody renamed the machine a while back (not shure who/when)

	
The IPs are 

iojs-softlayer-benchmark - 50.23.85.254
iojs-softlayer-benchmark-data - 50.97.245.4

I'd have to look in the current ansible inventory to find the corresponding name.  heading into a meeting so posting the IPs so you don't have to wait on that.

**Comment by mhdawson** [comment]
And I guess iojs-softlayer-benchmark-data never made it into the ansible inventory.  We did have issues to do that but they never were completed.

**Comment by mhdawson** [comment]
@Trott let me know if you get to this today, otherwise I might find time later today to land/test

**Comment by Trott** [comment]
> @Trott let me know if you get to this today, otherwise I might find time later today to land/test

I'm at a conference with slow wifi, which has the upside of preventing me from multitasking too much. So I probably won't get to it today.

**Comment by mhdawson** [comment]
I'm going to land, then test and revert if things don't work.

**Comment by Trott** [comment]
Thanks! Sorry I didn't get around to handling this myself!

**Pull request merged**
